!a::SendInput ^a
!c::SendInput ^c
!f::SendInput ^f
!k::SendInput ^k
!l::SendInput ^l
!q::SendInput !{F4}
!r::SendInput ^r
!s::SendInput ^s
!t::SendInput ^t
!+t::SendInput ^+t
!v::SendInput ^v
!w::SendInput ^w
!x::SendInput ^x
!z::SendInput ^z
!+z::SendInput ^y
!1::SendInput ^1
!2::SendInput ^2
!3::SendInput ^3
!4::SendInput ^4
!5::SendInput ^5
!6::SendInput ^6
!7::SendInput ^7
!8::SendInput ^8
!9::SendInput ^9
!0::SendInput ^0
